project_name: manutd-ticket-checker
before:
  hooks:
    - go mod tidy
builds:
  - binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - id: linux/amd64
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "robertyoung/{{ .ProjectName }}:latest"
      - "robertyoung/{{ .ProjectName }}:{{ .Tag }}"
    build_flag_templates:
      - "--platform=linux/amd64"
  - id: linux/arm64
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "robertyoung/{{ .ProjectName }}:latest"
      - "robertyoung/{{ .ProjectName }}:{{ .Tag }}"
    build_flag_templates:
      - "--platform=linux/arm64"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
