on:
  release:
    types:
      - created
      - published
      - released

name: upload-release-artifacts
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Replace release artifact
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ github.ref_name }}"
          artifacts: dist/*
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
          allowUpdates: true
